name: Build, Test, and Push Docker

# Триггер для запуска пайплайна
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Задача запускается на ОС ubuntu
    runs-on: ubuntu-latest

    steps:
      # Это действие извлекает репозиторий из папки $GITHUB_WORKSPACE,
      #  чтобы рабочий процесс мог получить к нему доступ.
      - uses: actions/checkout@v3

      # Настройки java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Права на запуск gradlew
      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # билд проекта
      - name: Build project
        run: ./gradlew build -x test

      # Сохраняем jar как артефакт для других job
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-libs
          path: build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # Тест проекта
      - name: Run tests
        run: ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write   # нужно, чтобы пушить в GHCR
    steps:
      - uses: actions/checkout@v3

      # скачиваем собранный jar из job build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-libs
          path: build/libs

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercased repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LC }}/prometheus:sha-${{ github.sha }}